[package]
name = "thrustc_parser"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"
either = "1.15.0"
smallvec = "1.15.1"

thrustc_llvm_target_triple = { path = "../thrustc_llvm_target_triple" }

thrustc_backends = { path = "../thrustc_backends" }
thrustc_parser_context = { path = "../thrustc_parser_context" }
thrustc_parser_table = { path = "../thrustc_parser_table" }
thrustc_parser_external_table = { path = "../thrustc_parser_external_table" }
thrustc_generics = { path = "../thrustc_generics" }
thrustc_preprocessor = { path = "../thrustc_preprocessor" }
thrustc_entities = { path = "../thrustc_entities" }
thrustc_ast_modificators = { path = "../thrustc_ast_modificators" }
thrustc_mir = { path = "../thrustc_mir" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_builtins = { path = "../thrustc_builtins" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_options = { path = "../thrustc_options" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_code_location = { path = "../thrustc_code_location" }
thrustc_token = { path = "../thrustc_token" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_token_type = { path = "../thrustc_token_type" }
thrustc_constants = { path = "../thrustc_constants" }
thrustc_reader = { path = "../thrustc_reader" }
thrustc_lexer = { path = "../thrustc_lexer" }
