[package]
name = "thrustc_ast"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
colored = "3.0.0"
smallvec = "1.15.1"
serde = { version = "1.0.228", features = ["derive"] }
clipboard = { version = "0.5.0", optional = true }

thrustc_ast_external = { path = "../thrustc_ast_external"}
thrustc_span = { path = "../thrustc_span" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_ast_modificators = { path = "../thrustc_ast_modificators" }
thrustc_mir = { path = "../thrustc_mir" }
thrustc_token = { path = "../thrustc_token" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_token_type = { path = "../thrustc_token_type" }
thrustc_logging = { path = "../thrustc_logging" }

arbitrary =  { version = "1.4.2", features = ["derive"], optional = true }

[features]
fuzz = [
    "dep:arbitrary",
    "thrustc_span/fuzz",
    "thrustc_typesystem/fuzz",
    "thrustc_attributes/fuzz",
    "thrustc_token/fuzz",
    "thrustc_token_type/fuzz",
    "thrustc_ast_external/fuzz",
    "thrustc_ast_modificators/fuzz"
]