[changelog]
header = """
# Changelog\n
All notable changes to the Thrust Compiler (thrustc) are documented here.\n
"""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}\
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | upper_first }}\
{% if commit.breaking %} [**BREAKING**]{% endif %} \
([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/thrustlang/thrustc/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}\n
"""
footer = """
---
*Thrust Compiler (thrustc) Changelog*
"""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_parsers = [
  # --- Sintaxis combinatoria: (feat(...), fix(...)) ---
  { message = "^\\(.*feat\\(frontend\\).*\\)",           group = "Features",      scope = "frontend" },
  { message = "^\\(.*feat\\(llvm_backend\\).*\\)",       group = "Features",      scope = "llvm_backend" },
  { message = "^\\(.*feat\\(gcc_backend\\).*\\)",        group = "Features",      scope = "gcc_backend" },
  { message = "^\\(.*feat\\(llvm_linker_driver\\).*\\)", group = "Features",      scope = "llvm_linker_driver" },
  { message = "^\\(.*feat\\(abi\\).*\\)",                group = "Features",      scope = "abi" },
  { message = "^\\(.*feat\\(preprocessador\\).*\\)",     group = "Features",      scope = "preprocessador" },
  { message = "^\\(.*feat\\(project-visual\\).*\\)",     group = "Documentation", scope = "project-visual" },
  { message = "^\\(.*feat\\(project\\).*\\)",            group = "Project",       scope = "project" },
  { message = "^\\(.*feat\\(doc\\).*\\)",                group = "Documentation", scope = "doc" },
  { message = "^\\(.*fix\\(frontend\\).*\\)",            group = "Bug Fixes",     scope = "frontend" },
  { message = "^\\(.*fix\\(llvm_backend\\).*\\)",        group = "Bug Fixes",     scope = "llvm_backend" },
  { message = "^\\(.*fix\\(gcc_backend\\).*\\)",         group = "Bug Fixes",     scope = "gcc_backend" },
  { message = "^\\(.*fix\\(llvm_linker_driver\\).*\\)",  group = "Bug Fixes",     scope = "llvm_linker_driver" },
  { message = "^\\(.*fix\\(abi\\).*\\)",                 group = "Bug Fixes",     scope = "abi" },
  { message = "^\\(.*fix\\(preprocessador\\).*\\)",      group = "Bug Fixes",     scope = "preprocessador" },
  { message = "^\\(.*fix\\(project\\).*\\)",             group = "Bug Fixes",     scope = "project" },
  { message = "^\\(.*fix\\(doc\\).*\\)",                 group = "Bug Fixes",     scope = "doc" },

  # --- Sintaxis simple: feat(...) / fix(...) ---
  { message = "^feat\\(llvm_backend\\)",       group = "Features",      scope = "llvm_backend" },
  { message = "^feat\\(gcc_backend\\)",        group = "Features",      scope = "gcc_backend" },
  { message = "^feat\\(llvm_linker_driver\\)", group = "Features",      scope = "llvm_linker_driver" },
  { message = "^feat\\(abi\\)",                group = "Features",      scope = "abi" },
  { message = "^feat\\(preprocessador\\)",     group = "Features",      scope = "preprocessador" },
  { message = "^feat\\(frontend\\)",           group = "Features",      scope = "frontend" },
  { message = "^feat\\(project-visual\\)",     group = "Documentation", scope = "project-visual" },
  { message = "^feat\\(project\\)",            group = "Project",       scope = "project" },
  { message = "^feat\\(doc\\)",                group = "Documentation", scope = "doc" },
  { message = "^feat\\(",                      group = "Features" },
  { message = "^fix\\(llvm_backend\\)",        group = "Bug Fixes",     scope = "llvm_backend" },
  { message = "^fix\\(gcc_backend\\)",         group = "Bug Fixes",     scope = "gcc_backend" },
  { message = "^fix\\(llvm_linker_driver\\)",  group = "Bug Fixes",     scope = "llvm_linker_driver" },
  { message = "^fix\\(abi\\)",                 group = "Bug Fixes",     scope = "abi" },
  { message = "^fix\\(preprocessador\\)",      group = "Bug Fixes",     scope = "preprocessador" },
  { message = "^fix\\(frontend\\)",            group = "Bug Fixes",     scope = "frontend" },
  { message = "^fix\\(project-visual\\)",      group = "Bug Fixes",     scope = "project-visual" },
  { message = "^fix\\(project\\)",             group = "Bug Fixes",     scope = "project" },
  { message = "^fix\\(doc\\)",                 group = "Bug Fixes",     scope = "doc" },
  { message = "^fix\\(",                       group = "Bug Fixes" },
  { message = ".*", skip = true },
]
commit_preprocessors = [
  { pattern = "^Merge .*", replace = "" },
  { pattern = "^`", replace = "" },
  { pattern = "\\)`", replace = ")" }
]
filter_commits = true
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "newest"
link_parsers = [
  { pattern = "#(\\d+)", href = "https://github.com/thrustlang/thrustc/issues/$1" },
]