#ifndef IMPORT_C_HELPER_NUMERIC_MACROS_H
#define IMPORT_C_HELPER_NUMERIC_MACROS_H

#define LOCAL_NEGATIVE -5
#define LOCAL_HEX 0x2A
#define LOCAL_UNSIGNED 15U
#define LOCAL_FLOAT 0.5f
#define LOCAL_DOUBLE 1.25

#endif
