[package]
name = "thrustc_c_transpiler"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
clang = { workspace = true }

thrustc_c_import_synthesis = { path = "../thrustc_c_import_synthesis" }
thrustc_compile_time = { path = "../thrustc_compile_time" }
thrustc_code_location = { path = "../thrustc_code_location" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_options = { path = "../thrustc_options" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
