[package]
name = "thrustc_linter"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"

thrustc_constants = { path = "../thrustc_constants" }
thrustc_token = { path = "../thrustc_token" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_entities = { path = "../thrustc_entities" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_options = { path = "../thrustc_options" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_code_location = { path = "../thrustc_code_location" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_token_type = { path = "../thrustc_token_type" }