[package]
name = "thrustc_llvm_codegen"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"
fastrand = "2.3.0"
libloading = "0.8.9"
either = "1.15.0"
uuid = { version = "1.19.0", features = ["v4"] }

inkwell = { workspace = true, optional = true }
clang = { workspace = true, optional = true }

thrustc_llvm_abi = { path = "../thrustc_llvm_abi" }
thrustc_llvm_abi_representation = { path = "../thrustc_llvm_abi_representation" }
thrustc_llvm_target_triple = { path = "../thrustc_llvm_target_triple" }
thrustc_llvm_attributes = { path = "../thrustc_llvm_attributes" }
thrustc_llvm_callconventions = { path = "../thrustc_llvm_callconventions" }
thrustc_backends = { path = "../thrustc_backends" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_mir = { path = "../thrustc_mir" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_ast_external = { path = "../thrustc_ast_external" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_options = { path = "../thrustc_options" }
thrustc_entities = { path = "../thrustc_entities" }
thrustc_constants = { path = "../thrustc_constants" }
thrustc_token = { path = "../thrustc_token" }
thrustc_token_type = { path = "../thrustc_token_type" }
thrustc_span = { path = "../thrustc_span" }

[features]
default = ["llvm_backend_static"]

llvm_backend_dynamic = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-dynamic"]
llvm_backend_static  = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-static"]

cbindgen_static      = ["dep:clang", "clang/static"]
cbindgen_dynamic     = ["dep:clang"]
