[package]
name = "thrustc_heap_allocator"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
thrustc_logging = { path = "../thrustc_logging" }
thrustc_constants = { path = "../thrustc_constants" }