[package]
name = "thrustc_ast_modificators"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }

thrustc_atomic_ordering = { path = "../thrustc_atomic_ordering" }
thrustc_thread_mode = { path = "../thrustc_thread_mode" }

arbitrary =  { version = "1.4.2", features = ["derive"], optional = true }

[features]
fuzz = [
    "dep:arbitrary",
    "thrustc_atomic_ordering/fuzz",
    "thrustc_thread_mode/fuzz"
]
