[build]
rustc-wrapper = "sccache"

rustflags = [
    "-A", "missing_abi",
    "-A", "dead_code",
    "-A", "clippy::enum_variant_names",
    "-A", "elided_lifetimes_in_paths",
    "-A", "clippy::new_without_default"
]

[alias]
fuzz-llvm-stable = "fuzz run llvm-codegen fuzz/corpus_stable/llvm-codegen -- -dict=fuzz/thrust-stable.dict -- --stable"
fuzz-llvm-unstable = "fuzz run llvm-codegen fuzz/corpus_unstable/llvm-codegen -- -dict=fuzz/thrust-unstable.dict"

fuzz-pipeline-stable = "fuzz run pipeline fuzz/corpus_stable/pipeline -- -dict=fuzz/thrust-stable.dict -- --stable"
fuzz-pipeline-unstable = "fuzz run pipeline fuzz/corpus_unstable/pipeline -- -dict=fuzz/thrust-unstable.dict"

fuzz-lexer = "fuzz run lexer fuzz/corpus_universal/lexer -- -dict=fuzz/thrust-stable.dict"
fuzz-dump-ast = "run --manifest-path fuzz/Cargo.toml --bin dump_ast"
fuzz-reproduce-case = "run --manifest-path fuzz/Cargo.toml --bin reproduce"

docs = "doc --workspace --no-deps --document-private-items --exclude clang --exclude inkwell --exclude inkwell_internals --exclude llvm-sys --exclude clang-sys"
docs-open = "doc --workspace --no-deps --document-private-items --open --exclude clang --exclude inkwell --exclude inkwell_internals --exclude llvm-sys --exclude clang-sys"

[lints.clippy]
style     = "allow"
complexity = "allow"
pedantic  = "allow"
new_without_default = "allow"