[build]
rustc-wrapper = "sccache"

rustflags = [
    "-A", "missing_abi",
    "-A", "dead_code",
    "-A", "clippy::enum_variant_names",
    "-A", "elided_lifetimes_in_paths",
    "-A", "clippy::new_without_default"
]

[alias]
fuzz-llvm-top-level-stable = "fuzz run llvm-codegen-top-level fuzz/corpus_stable/llvm-codegen-top-level -- -dict=fuzz/thrust-stable.dict -rss_limit_mb=2048 -- --stable"
fuzz-llvm-top-level-unstable = "fuzz run llvm-codegen-top-level fuzz/corpus_unstable/llvm-codegen-top-level -- -dict=fuzz/thrust-unstable.dict -rss_limit_mb=2048"

fuzz-llvm-local-stable = "fuzz run llvm-codegen-local fuzz/corpus_stable/llvm-codegen-local -- -dict=fuzz/thrust-stable.dict -rss_limit_mb=4096 -- --stable"
fuzz-llvm-local-unstable = "fuzz run llvm-codegen-local fuzz/corpus_unstable/llvm-codegen-local -- -dict=fuzz/thrust-unstable.dict -rss_limit_mb=2048"

fuzz-llvm-local-loops-unstable = "fuzz run llvm-codegen-local-loops fuzz/corpus_unstable/llvm-codegen-local-loops -- -dict=fuzz/thrust-unstable.dict -rss_limit_mb=2048"
fuzz-llvm-local-loops-stable = "fuzz run llvm-codegen-local-loops fuzz/corpus_stable/llvm-codegen-local-loops -- -dict=fuzz/thrust-stable.dict -rss_limit_mb=4096 -- --stable"

fuzz-pipeline-stable = "fuzz run pipeline fuzz/corpus_stable/pipeline -- -dict=fuzz/thrust-stable.dict -rss_limit_mb=2048 -- --stable"
fuzz-pipeline-unstable = "fuzz run pipeline fuzz/corpus_unstable/pipeline -- -dict=fuzz/thrust-unstable.dict -rss_limit_mb=2048"

fuzz-lexer = "fuzz run lexer fuzz/corpus_universal/lexer -- -dict=fuzz/thrust-stable.dict -rss_limit_mb=2048" 

fuzz-dump-ast-top-level = "run --manifest-path fuzz/Cargo.toml --bin dump_ast_top_level"
fuzz-dump-ast-local = "run --manifest-path fuzz/Cargo.toml --bin dump_ast_local"
fuzz-dump-ast-local-loops = "run --manifest-path fuzz/Cargo.toml --bin dump_ast_local_loops"
fuzz-dump-llvm-ir = "run --manifest-path fuzz/Cargo.toml --bin dump_llvm_ir"
fuzz-reproduce-case = "run --manifest-path fuzz/Cargo.toml --bin reproduce"

fuzz-continuous = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor"
fuzz-backlog = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor"
fuzz-continuous-llvm-top-level-stable = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run llvm-codegen-top-level --mode stable"
fuzz-continuous-llvm-top-level-unstable = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run llvm-codegen-top-level --mode unstable"
fuzz-continuous-llvm-local-stable = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run llvm-codegen-local --mode stable"
fuzz-continuous-llvm-local-unstable = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run llvm-codegen-local --mode unstable"
fuzz-continuous-llvm-local-loops-stable = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run llvm-codegen-local-loops --mode stable"
fuzz-continuous-llvm-local-loops-unstable = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run llvm-codegen-local-loops --mode unstable"
fuzz-continuous-pipeline-stable = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run pipeline --mode stable"
fuzz-continuous-pipeline-unstable = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run pipeline --mode unstable"
fuzz-continuous-lexer = "run --manifest-path fuzz/Cargo.toml --bin fuzz_supervisor -- run lexer"

docs = "doc --workspace --no-deps --document-private-items --exclude clang --exclude inkwell --exclude inkwell_internals --exclude llvm-sys --exclude clang-sys"
docs-open = "doc --workspace --no-deps --document-private-items --open --exclude clang --exclude inkwell --exclude inkwell_internals --exclude llvm-sys --exclude clang-sys"

[lints.clippy]
style     = "allow"
complexity = "allow"
pedantic  = "allow"
new_without_default = "allow"