[build]
rustc-wrapper = "sccache"

rustflags = [
    "-A", "missing_abi",
    "-A", "dead_code",
    "-A", "clippy::enum_variant_names",
    "-A", "elided_lifetimes_in_paths",
    "-A", "clippy::new_without_default"
]

[alias]
# Compiler Fuzzing
fuzz-llvm = "fuzz run llvm-codegen -- -dict=fuzz/thrust.dict"
fuzz-pipeline = "fuzz run pipeline -- -dict=fuzz/thrust.dict"

# Rust code documentation
docs = "doc --workspace --no-deps --document-private-items --exclude clang --exclude inkwell --exclude inkwell_internals --exclude llvm-sys --exclude clang-sys"
docs-open = "doc --workspace --no-deps --document-private-items --open --exclude clang --exclude inkwell --exclude inkwell_internals --exclude llvm-sys --exclude clang-sys"

[lints.clippy]
style     = "allow"
complexity = "allow"
pedantic  = "allow"
new_without_default = "allow"