[package]
name = "thrustc_entities"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"
smallvec = "1.15.1"

thrustc_ast = { path = "../thrustc_ast" }
thrustc_span = { path = "../thrustc_span" }
thrustc_token = { path = "../thrustc_token" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_token_type = { path = "../thrustc_token_type" }