[package]
name = "thrustc_span"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
arbitrary =  { version = "1.4.2", features = ["derive"], optional = true }

[features]
fuzz = ["dep:arbitrary"]