[package]
name = "thrustc_llvm_attributes"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"

inkwell = { workspace = true, optional = true }
clang = { workspace = true, optional = true }

thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_span = { path = "../thrustc_span" }
thrustc_llvm_callconventions = { path = "../thrustc_llvm_callconventions" }

[features]
default = ["llvm_backend_static"]

llvm_backend_dynamic = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-dynamic"]
llvm_backend_static  = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-static"]

cbindgen_static      = ["dep:clang", "clang/static"]
cbindgen_dynamic     = ["dep:clang"]
