[package]
name = "thrustc_ast_external"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }

thrustc_code_location = { path = "../thrustc_code_location" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_attributes = { path = "../thrustc_attributes" }

arbitrary =  { version = "1.4.2", features = ["derive"], optional = true }

[features]
fuzz = [
    "dep:arbitrary",
    "thrustc_code_location/fuzz",
    "thrustc_typesystem/fuzz",
    "thrustc_attributes/fuzz",
]