[package]
name = "thrustc_options"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
libloading = "0.8.9"
uuid = { version = "1.19.0", features = ["v4"] }

inkwell = { workspace = true, optional = true }
clang = { workspace = true, optional = true }

thrustc_backends = { path = "../thrustc_backends" }
thrustc_abi = { path = "../thrustc_abi" }
thrustc_llvm_target_triple = { path = "../thrustc_llvm_target_triple"}
thrustc_token = { path = "../thrustc_token" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_span = { path = "../thrustc_span" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_errors = { path = "../thrustc_errors" }

[features]
default = ["llvm_backend_static"]

llvm_backend_dynamic = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-dynamic"]
llvm_backend_static  = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-static"]

cbindgen_static      = ["dep:clang", "clang/static"]
cbindgen_dynamic     = ["dep:clang"]
