[package]
name = "thrustc_attributes"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"
serde = { version = "1.0.228", features = ["derive"] }

inkwell = { workspace = true, optional = true }
clang = { workspace = true, optional = true }

thrustc_logging = { path = "../thrustc_logging" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_span = { path = "../thrustc_span" }
thrustc_token = { path = "../thrustc_token" }
thrustc_token_type = { path = "../thrustc_token_type" }
thrustc_typesystem = { path = "../thrustc_typesystem" }

arbitrary =  { version = "1.4.2", features = ["derive"], optional = true }

[features]
default = ["llvm_backend_static"]

llvm_backend_dynamic = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-dynamic"]
llvm_backend_static  = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-static"]

cbindgen_static      = ["dep:clang", "clang/static"]
cbindgen_dynamic     = ["dep:clang"]

fuzz                 = ["dep:arbitrary"]
