[package]
name = "thrustc_semantic"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
either = "1.15.0"

thrustc_ast = { path = "../thrustc_ast" }
thrustc_ast_verifier = { path = "../thrustc_ast_verifier" }
thrustc_options = { path = "../thrustc_options" }
thrustc_general_analyzer = { path = "../thrustc_general_analyzer" }
thrustc_typechecker = { path = "../thrustc_typechecker" }
thrustc_scoper = { path = "../thrustc_scoper" }
thrustc_attribute_checker = { path = "../thrustc_attribute_checker" }
thrustc_linter = { path = "../thrustc_linter" }