[package]
name = "thrustc_core"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
fastrand = "2.3.0"
either = "1.15.0"
colored = "3.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
syntect = "5.3.0"

inkwell = { workspace = true, optional = true }
clang = { workspace = true, optional = true }

clipboard = { version = "0.5.0", optional = true }

thrustc_llvm_abi = { path = "../thrustc_llvm_abi" }
thrustc_llvm_abi_representation = { path = "../thrustc_llvm_abi_representation" }
thrustc_backends = { path = "../thrustc_backends" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_preprocessor = { path = "../thrustc_preprocessor" }
thrustc_llvm_call_conventions_checker = { path = "../thrustc_llvm_call_conventions_checker" }
thrustc_llvm_compiler_intrinsic_checker = { path = "../thrustc_llvm_compiler_intrinsic_checker" }
thrustc_llvm_target_triple = { path = "../thrustc_llvm_target_triple" }
thrustc_constants = { path = "../thrustc_constants" }
thrustc_token = { path = "../thrustc_token" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_lexer = { path = "../thrustc_lexer" }
thrustc_parser = { path = "../thrustc_parser" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_options = { path = "../thrustc_options" }
thrustc_semantic_analysis = { path = "../thrustc_semantic_analysis" }
thrustc_llvm_codegen = { path = "../thrustc_llvm_codegen" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_utils = { path = "../thrustc_utils" }

[features]
default = ["llvm_backend_static"]

llvm_backend_dynamic = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-dynamic"]
llvm_backend_static  = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-static"]

cbindgen_static      = ["dep:clang", "clang/static"]
cbindgen_dynamic     = ["dep:clang"]

extra_utilities = ["dep:clipboard"]


