[package]
name = "thrustc_typesystem"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"
either = "1.15.0"
serde = { version = "1.0.228", features = ["derive"] }

thrustc_span = { path = "../thrustc_span" }
thrustc_token_type = { path = "../thrustc_token_type" }

thrustc_llvm_target_triple = { path = "../thrustc_llvm_target_triple" }

arbitrary =  { version = "1.4.2", features = ["derive"], optional = true }

[features]
fuzz = ["dep:arbitrary"]