[package]
name = "thrustc_general_analyzer"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]

thrustc_constants = { path = "../thrustc_constants" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_token_type = { path = "../thrustc_token_type" }
thrustc_options = { path = "../thrustc_options" }
thrustc_directive = { path = "../thrustc_directive" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_code_location = { path = "../thrustc_code_location" }
thrustc_typesystem = { path = "../thrustc_typesystem" }